name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature to improve this integration!
  - type: input
    id: integration_version
    attributes:
      label: Integration version
      description: What version of deepgram_tts are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Why is this feature important to you? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or features?
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
